# 1.创建

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array((5, 6, 7, 8))
c = np.array([[1, 2, 3, 4],
             [4, 5, 6, 7],
             [7, 8, 9, 10]])
a, b, c

(array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]))

In [3]:
a.shape, b.shape, c.shape

((4,), (4,), (3, 4))

In [4]:
c.shape = (4, 3)
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [5]:
c.shape = 2, -1
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

当设置某个轴的元素为 **-1** 时，将自动计算此轴的长度。

In [6]:
d = a.reshape((2, 2)) #也可以用a.reshape(2, 2)
d

array([[1, 2],
       [3, 4]])

数组 a 和 d 其实共享数据存储空间， 因此修改其中任意一个数组的元素都会同时修另一个数组的内容

In [7]:
a[1] = 100
a, d

(array([  1, 100,   3,   4]), array([[  1, 100],
        [  3,   4]]))

# 2.元素类型

In [8]:
c.dtype

dtype('int32')

默认32位长整型（根据使用的python是32位）

In [9]:
ai32 = np.array([1,2,3,4],dtype=np.float32)
ai32.dtype

dtype('float32')

In [10]:
[key for key, value in np.typeDict.items() if value is np.float32]

['f', 11, 'float32', 'Float32', 'f4', 'single']

Numpy中的每个数值类型都有几种字符串表示方式，字符串和类型之间的对应关系都存储在typeDict字典中

In [11]:
set(np.typeDict.values())

{numpy.bool_,
 numpy.bytes_,
 numpy.complex128,
 numpy.complex128,
 numpy.complex64,
 numpy.datetime64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float64,
 numpy.int16,
 numpy.int32,
 numpy.int32,
 numpy.int64,
 numpy.int8,
 numpy.object_,
 numpy.str_,
 numpy.timedelta64,
 numpy.uint16,
 numpy.uint32,
 numpy.uint32,
 numpy.uint64,
 numpy.uint8,
 numpy.void}

上面显示的数值类型与数组的dtype属性是不同的对象。通过dtype对象的type属性可以获取与其对用的数值类型。

In [12]:
c.dtype,c.dtype.type

(dtype('int32'), numpy.int32)

In [13]:
a = np.int16(200)

In [14]:
a*a

E:\Study\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in short_scalars
  """Entry point for launching an IPython kernel.


-25536

数据溢出

In [15]:
v1 = 3.14
v2 = np.float32(v1)
%timeit v1**2
%timeit v2**2

141 ns ± 5.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
1.91 µs ± 47.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


特别注意，Numpy对象的数值运算速度比Python的内置类型的运算速度慢很多。

In [16]:
t1 = np.array([1,2,3,4],dtype=np.float)
t2 = np.array([1,2,3,4],dtype=np.complex)
t3 = t1.astype(np.int32)
t4 = t2.astype(np.complex64)

使用astype()方法可以对数组元素类型进行转换。

# 3.自动生成数组

In [17]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

自拟原型 `arange(start, stop, step)`

In [18]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

自拟原型 `linspace(start, stop, number)`

In [19]:
np.linspace(0, 1, 10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

`endpoint`的值会改变数组的等差步长

In [20]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

等比数列，从10^0到10^2，产生5个元素的等比数列，且同样可以指定`endpoint`的值。

In [21]:
np.empty((2,3), np,int), np.zeros(4, np.int), np.full(4, np.pi)

E:\Study\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


(array([[None, None, None],
        [None, None, None]], dtype=object),
 array([0, 0, 0, 0]),
 array([3.14159265, 3.14159265, 3.14159265, 3.14159265]))

其中`empty()`方法只分配空间。
此外，`zeros_like(), ones_like(), empty_like(), full_like()`等方法效果相同。

In [22]:
def func(i):
    return i % 4 +1

In [23]:
np.fromfunction(func, (10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])


# 4.存储元素

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a[5],a[3:5],a[:5],a[:-1]

(5, array([3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [26]:
a[1:-1:2],a[::-1],a[5:1:-2]

(array([1, 3, 5, 7]), array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]), array([5, 3]))

In [27]:
a[2:4] = 100,101
a

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

In [28]:
b = a[3:7]
b[2] = -10
a,b

(array([  0,   1, 100, 101,   4, -10,   6,   7,   8,   9]),
 array([101,   4, -10,   6]))

共享内存

In [29]:
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [30]:
a = x[[3,3,1,8]]
b = x[[3,3,-3,8]]
a,b

(array([7, 7, 9, 2]), array([7, 7, 4, 2]))

In [31]:
b[2] = 100
b,x

(array([  7,   7, 100,   2]), array([10,  9,  8,  7,  6,  5,  4,  3,  2]))

不共享内存

In [32]:
x[[3,5,1]] = -1,-2,-3
x

array([10, -3,  8, -1,  6, -2,  4,  3,  2])

In [33]:
x = np.arange(10,1,-1)
x[np.array([[3,3,1,8],[3,3,-3,8]])]

array([[7, 7, 9, 2],
       [7, 7, 4, 2]])

In [34]:
x[[3,3,1,8,3,3,-3,8]].reshape(2,4)

array([[7, 7, 9, 2],
       [7, 7, 4, 2]])

In [35]:
x = np.arange(5,0,-1)
x

array([5, 4, 3, 2, 1])

In [36]:
x[np.array([True,False,True,False,False])]

array([5, 3])

In [37]:
x[[True,False,True,False,False]]

array([5, 3])

In [38]:
x[x>3]

array([5, 4])

# 5.多维数组

In [39]:
a = np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [40]:
a[0,3:5],a[4:,4:],a[:,2],a[2::2,::2]

(array([3, 4]), array([[44, 45],
        [54, 55]]), array([ 2, 12, 22, 32, 42, 52]), array([[20, 22, 24],
        [40, 42, 44]]))

In [41]:
b = a[0, 3:5]
b[0] = -b[0]
a[0, 3:5]

array([-3,  4])

共享内存

In [42]:
idx = slice(None, None, 2), slice(2, None)
a[idx],a[idx][idx]

(array([[ 2, -3,  4,  5],
        [22, 23, 24, 25],
        [42, 43, 44, 45]]), array([[ 4,  5],
        [44, 45]]))

`a[idx] == a[::2, 2:], a[idx][idx] == a[::2, 2:][::2, 2:] `
slice()创建切片

In [43]:
np.s_[::2, 2:]

(slice(None, None, 2), slice(2, None, None))

In [44]:
a[(0,1,2,3),(1,2,3,4)]

array([ 1, 12, 23, 34])

`a[0,1],a[1,2],a[2,3],a[3,4]`

In [45]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [46]:
mask = np.array([1,0,1,0,0,1],dtype=np.bool)
a[mask, 2]

array([ 2, 22, 52])

In [47]:
mask1 = np.array([1,0,1,0,0,1])
mask2 = [True,False,True,False,False,True]
a[mask1,2],a[mask2,2]

(array([12,  2, 12,  2,  2, 12]), array([ 2, 22, 52]))

In [48]:
a[[1,2],:],a[[1,2]]

(array([[10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25]]), array([[10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25]]))

In [49]:
x = np.array([[0,1],[2,3]])
y = np.array([[-1,-2],[-3,-4]])
a[x,y]

array([[ 5, 14],
       [23, 32]])

In [50]:
a[(0,1,2,3),(-1,-2,-3,-4)].reshape(2,2)

array([[ 5, 14],
       [23, 32]])

In [51]:
a[x]

array([[[ 0,  1,  2, -3,  4,  5],
        [10, 11, 12, 13, 14, 15]],

       [[20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35]]])

In [52]:
palette = np.array([[0,0,0],
                    [255,0,0],
                    [0,255,0],
                    [0,0,255],
                    [255,255,255]])
image = np.array([[0,1,2,0],
                  [0,3,4,0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

# 6.结构数组

In [54]:
persontype = np.dtype({'names':['name','age','weight'],
                       'formats':['S30','i', 'f']},align = True)

In [57]:
a = np.array([("Zhang", 32, 75.5),("He", 18, 49.5)],dtype=persontype)
a

array([(b'Zhang', 32, 75.5), (b'He', 18, 49.5)],
      dtype={'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True})

In [58]:
a.dtype

dtype({'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40}, align=True)

In [59]:
a[0].dtype

dtype({'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40}, align=True)

In [64]:
a[0]["name"]

b'Zhang'