In [3]:
from sklearn import preprocessing
import numpy as np
X = np.array([[1., -2., 2.],
              [3., 0., 0.],
              [0., 1., -1.]])
X

array([[ 1., -2.,  2.],
       [ 3.,  0.,  0.],
       [ 0.,  1., -1.]])

In [4]:
X_scaled = preprocessing.scale(X)
X_scaled
#标准化矩阵
#零均值，单位方差
#计算 (x-u)/o (u表示平均值，o表示方差)

array([[-0.26726124, -1.33630621,  1.33630621],
       [ 1.33630621,  0.26726124, -0.26726124],
       [-1.06904497,  1.06904497, -1.06904497]])

In [5]:
X_scaled.mean(axis=0)
#计算每行均值--接近或等于0

array([7.40148683e-17, 0.00000000e+00, 0.00000000e+00])

In [7]:
X_scaled.std(axis=0)
#计算每行方差

array([1., 1., 1.])

In [9]:
X_normalized_l1 = preprocessing.normalize(X, norm='l1')
X_normalized_l1
#归一化操作
#缩放单个样本使它们拥有单位范数
#此代码段表示计算L1范数--曼哈顿距离--绝对值和成比例

array([[ 0.2, -0.4,  0.4],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.5, -0.5]])

In [10]:
X_normalized_l2 = preprocessing.normalize(X, norm='l2')
X_normalized_l2
#计算L2范数--欧氏距离--所有平方和成比例

array([[ 0.33333333, -0.66666667,  0.66666667],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [11]:
min_max_scaler = preprocessing.MinMaxScaler()
X_min_max = min_max_scaler.fit_transform(X)
X_min_max
#缩放到0和1之间

array([[0.33333333, 0.        , 1.        ],
       [1.        , 0.66666667, 0.33333333],
       [0.        , 1.        , 0.        ]])

In [12]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-10, 10))
X_min_max = min_max_scaler.fit_transform(X)
X_min_max
#缩放到-10和10之间

array([[ -3.33333333, -10.        ,  10.        ],
       [ 10.        ,   3.33333333,  -3.33333333],
       [-10.        ,  10.        , -10.        ]])

In [14]:
binarizer = preprocessing.Binarizer(threshold=0.5)
X_binarizer = binarizer.transform(X)
X_binarizer
#设置阈值0.5进行二值化

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [17]:
A = np.array([[np.nan, 0, 3],
              [2, 9, -8],
              [1,np.nan, 1],
              [5, 2, 4],
              [7, 6, -3]])
A

array([[nan,  0.,  3.],
       [ 2.,  9., -8.],
       [ 1., nan,  1.],
       [ 5.,  2.,  4.],
       [ 7.,  6., -3.]])

In [20]:
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X2 = imp.fit_transform(A)
X2
#strategy参数：'mean' 'median' 'most_frequest'表示取对应列（默认nan所在列）的均值，中值，最高频值

array([[ 3.75,  0.  ,  3.  ],
       [ 2.  ,  9.  , -8.  ],
       [ 1.  ,  4.25,  1.  ],
       [ 5.  ,  2.  ,  4.  ],
       [ 7.  ,  6.  , -3.  ]])